import type { Metadata } from "next";
import "../styles/globals.css";

export const metadata: Metadata = {
  title: "Anveshana '25",
  description: "Generated by IIC BMSIT",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
