import Header from "@/components/Header";
import ActiveSectionContextProvider from "@/context/active-section-context";
import type { Metadata } from "next";
import "../styles/globals.css";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Anveshana '25",
  description: "Generated by IIC BMSIT",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ActiveSectionContextProvider>
          <Header />
          {children}
          <Footer />
        </ActiveSectionContextProvider>
      </body>
    </html>
  );
}
